### ISSUE TITLE
Although official repo, not the latest version on Github

### ISSUE THREAD

**Issue by TAbdiukov** [zuckschwerdt/obexftp#2]
It seems like not the latest version uploaded.

In `CHANGELOG`, the top entry says,
```
ObexFTP 0.23 (released 2009-02-17)
----------------------------------
```

However, the source code found on Sourceforge contains a changelog that says

```
ObexFTP 0.24.2 (released 2016-04-07)
------------------------------------

	* obexfs: Parse XML data with Expat library
	* obexfs: Properly encode XML special characters
	* obexfs: New option -r to specify root path
	* obexfs: New option -S to simulate free space
	* Fix probing
	* Add support for Gigaset devices
	* CMake improvements
...
```

It seems like, although this is the official repository, the source code is not the latest (i.e. outdated) here on Github

**Comment by zuckschwerdt** [comment]
Though I'm the original author the project is maintained by Hendrik Sattler now. The official repo should be https://gitlab.com/obexftp/mainline
I'll mirror those changes back here and perhaps add a note so this is less confusing.

**Comment by TAbdiukov** [comment]
Oh thanks! A bit confusing indeed

P.S. I know this is off-topic, but can I ask you or Hendrik Sattler to compile the last version executable for Win32/Win64/Win-anything? The last win32 version saved by archive.org is [from 2008](https://web.archive.org/web/20160813113317/http://triq.net/obexftp/) . I've spent a day trying to compile the executable with no luck, after not being able to get IrDA to work on modern Ubuntu..

P.P.S. You may find worth knowing that [dev.zuckschwerdt.org](http://dev.zuckschwerdt.org) is down :slightly_smiling_face:

**Comment by zuckschwerdt** [comment]
I don't have the compiler setup for win32 builds, sorry.
The server with docs is up, but you might be blocked as the abuse filters there are quite strict and lasting. If you give me an IP prefix I can check that.

**Comment by zuckschwerdt** [comment]
Synced with Hendriks Gitlab now.
