### ISSUE TITLE
There there known possible way to change file permissions through OBEX?

### ISSUE THREAD

**Issue by TAbdiukov** [zuckschwerdt/obexftp#3]
I discovered (with WireShark on the official software) that the other device successfully returns `telecom/devinfo.txt` if these flags are being used,
```
-U IRMC -S 
```
I noticed that the tool returns XML-formatted listings. [Here, for example]( http://dev.zuckschwerdt.org/openobex/wiki/ObexFtpExamples/)
```
<?xml version="1.0"?>
<!DOCTYPE folder-listing SYSTEM "obex-folder-listing.dtd">
<folder-listing version="1.0">
  <folder name="Address book" modified="20020101T002700" user-perm="WD" group-perm="W" />
  [...]
</folder-listing>
```
I wonder, now that I found a way to access `telecom/` (and possibly other hidden locations), there there known ways to edit these XML files and in particular the permissions recorded on them? There is absolutely NO information about it online...

P.S. I forgot to respond - can you please unban my IP? I'm pretty suyre I never did anything bad, in fact, I don't think I ever had a chance to access the website. My IP address is within,
`220.233.*.*`

**Comment by zuckschwerdt** [comment]
This isn't actively developed anymore, sorry.

If you are asking about my server, only 220.233.24.60 and 220.233.104.127 are currently blocked, via [FIREHOL cleantalk](http://iplists.firehol.org/?ipset=cleantalk_7d).

**Comment by TAbdiukov** [comment]
thanks!
